CONTACTS_PROTOTYPES = [
    # Registrar
    "how do i contact the registrar",
    "registrar office contact",
    "where is the registrar office",
    "who do i email about transcripts",
    "registrar phone number",
    # Admissions
    "admissions office contact",
    "graduate admissions contact",
    "who handles admissions",
    "admissions office phone number",
    # Financial offices
    "financial aid office phone number",
    "who manages student accounts",
    "bursar office contact",
    "student accounting office email",
    # Specific colleges and departments
    "armour college of engineering contact",
    "college of computing contact info",
    "chicago-kent college of law contact",
    "college of architecture contact",
    "stuart school of business contact",
    "department of computer science contact",
    "department of physics phone number",
    "department of chemistry email",
    "department of biology contact",
    "department of applied mathematics contact",
    "department of psychology contact",
    "biomedical engineering department contact",
    "chemical and biological engineering department contact",
    "electrical and computer engineering contact",
    "department of IT and management contact",
    "civil architectural environmental engineering contact",
    "ed kaplan institute contact",
    "english language services contact",
    "food science and nutrition contact",
    "empowerment leadership mentorship program contact",
    "mechanical materials aerospace engineering contact",
    "institute of design contact",
    "lewis college of science and letters contact",
    "illinois tech mumbai contact",
    "army rotc contact",
    "navy rotc contact",
    # Role-based lookups — specific enough
    "who handles transfer credit",
    "who handles probation appeals",
    "student services contact",
    "what is the IT help desk phone number",
    "who do i talk to about graduate programs",
    "wanger institute contact",
    "pritzker institute contact",
    "institute for food safety and health contact",
    # Contrastive — contact lookup vs policy question
    "how do i reach the physics department",
    "what is the email for computer science department",
    "phone number for stuart school of business",
    "fax number for department of chemistry",
    "where is the department of physics located",
    "where is the college of computing office",
    "contact information for armour college",
]
