DOCUMENTS_PROTOTYPES = [
    # Student handbook / co-terminal
    "what does the student handbook say",
    "co-terminal student handbook policies",
    "what are the co-terminal program rules",
    "what is the coterminal program",
    # Graduate academic policies
    "graduate academic policies",
    "what is the gpa requirement for graduation",
    "academic probation policy",
    "minimum gpa requirement",
    "academic standing rules",
    "how probation works university",
    "policy for academic dismissal",
    "grading policy university",
    "grade legend explanation",
    "what grades count toward gpa",
    "honors graduation requirements",
    "credit hour requirements",
    # Transcripts
    "how do i request a transcript",
    "official transcript request",
    "unofficial transcript illinois tech",
    "parchment transcript order",
    "how long does it take to get a transcript",
    "transcript fee cost",
    "transcript hold on account",
    "electronic transcript delivery",
    "transcript for employment verification",
    "how to get my academic records",
    # Registration policies
    "registration rules",
    "policy for dropping a course",
    "withdrawal policy university",
    "leave of absence policy",
    "course repeat policy",
    "transfer credit rules",
    "incomplete grade policy",
    "auditing a course rules",
    # Registrar policies
    "what is the hardship withdrawal process",
    "policies hardship",
    "registrar academic policies",
    "registration hold on my account",
    "how do i clear a hold",
    # Financial aid policies
    "financial aid academic requirements",
    "financial responsibility policy",
    "satisfactory academic progress policy",
    # Conduct and integrity
    "student conduct rules",
    "academic integrity policy",
    "what happens if i cheat",
    "plagiarism consequences",
    "code of conduct university",
    "alcohol and drug policy",
    "what is the amnesty policy",
    "FERPA student records policy",
    "title ix policy",
    "sexual misconduct policy",
    "disciplinary sanctions",
    "disruptive conduct policy",
    # Commencement and graduation
    "commencement policies",
    "graduation requirements university",
    "degree conferral requirements",
    # Coursera / events
    "coursera program policies",
    "events and schedules policy",
    "student directory policies",
    # ID and campus access
    "hawkcard policy",
    "student id card rules",
    "campus id card illinois tech",
    "can i lend my hawkcard",
    "lost hawkcard replacement",
    # Campus alerts and safety
    "iitalert notification system",
    "campus emergency alert",
    "how does iitalert work",
    "campus safety notifications",
    # Student support services
    "confidential advisor services",
    "sexual misconduct reporting",
    "resilience confidential advisor",
    "community affairs office",
    "volunteer opportunities campus",
    # Fraternities and sororities
    "fraternities sororities illinois tech",
    "greek life illinois tech",
    "how many fraternities illinois tech",
    "fraternity chapter house",
    "greek council recognition",
    # Grade types
    "na grade non attendance",
    "incomplete grade undergraduate",
    "incomplete grade graduate",
    "grade appeal process",
    "change of grade policy",
    # Transfer and credit
    "transfer credit policy",
    "external transfer credit",
    "doctoral transfer credit",
    "masters transfer credit",
    "unaccredited institution transfer",
    # Co-terminal specific
    "co-terminal financial aid",
    "co-terminal scholarship extension",
    "co-terminal federal aid",
    "co-terminal gpa requirement",
    "co-terminal advising",
    # Health insurance
    "student health insurance requirement",
    "ship health insurance",
    "international student insurance",
    "health insurance waiver",
    # Registration specifics
    "registration pin illinois tech",
    "enrollment verification",
    "national student clearinghouse",
    "degree verification",
    # Housing and residence
    "residence requirements undergraduate",
    "on campus housing policy",
    "housing guarantee",
    # Conduct appeals
    "appeal academic honesty decision",
    "code of conduct appeal",
    "expulsion review process",
    "suspension appeal",
    # Intellectual property
    "intellectual property policy",
    "student research ownership",
    "third party sponsorship work",
]
